### PR TITLE
refactor: v3.0

### LINKED ISSUE #86: mixin processing returns incorrect selector
* Node Version: v6.8.0
* NPM Version: 4.6.1
* postcss-less Version: 1.1.0

### LESS

```less
.test({
	.hello {
		.test {
		}
	}

	.fred {
	}
})
```

### JavaScript

```js
postcss()
  .process(lessText, { syntax })
  .then(function (result) {
    console.log(result.root.nodes[0].selector)
});
```

### Expected Behavior

Expected selector to not include mixin parameter

### Actual Behavior

selector includes entire parameter

### How can we reproduce the behavior?

Using code above

Note: It's possible I do not understand how the parsed output is supposed to look for the provided less content.

### LINKED ISSUE #88: Unexpectedly ignored words in @import
* Node Version: 8.3.0
* NPM Version: 5.3.0
* postcss-less Version: 1.1.0

### LESS

```less
@import missing "missing" "not missing";
```

### JavaScript

```js
require("postcss-less").parse('@import missing "missing" "not missing";')
```

### Expected Behavior

Error thrown, or `missing` and `"missing"` being somewhere on the `Import` node.

Note: The example code is invalid Less ("malformed import statement").

### Actual Behavior

The example Less code parses the same as this:

```less
@import "not missing";
```

In other words, `missing` and `"missing"` are totally ignored.

### How can we reproduce the behavior?

```js
require("postcss-less").parse('@import missing "missing" "not missing";')
```

### Background

This causes problems for [Prettier](https://github.com/prettier/prettier/) when people forget the semicolon after the `@import`: prettier/prettier#2584

```less
@import "../assets/font/league-gothic/league-gothic.css"

.ManagerPage {
  height: 100%;
}
```

... is turned into this by Prettier:

```less
@import .ManagerPage {
  height: 100%;
}
```

... because `"../assets/font/league-gothic/league-gothic.css"` is entirely missing from the AST. Prettier would need:

- Either an error to be thrown
- or `"../assets/font/league-gothic/league-gothic.css"` being somewhere on the `Import` node so that it can be printed back.

### LINKED ISSUE #89: CSS spec compliance: `!IMPORTANT` is valid – should be case insensitive
* Node Version: 8.3.0
* NPM Version: 5.3.0
* postcss-less Version: 1.1.0

### LESS

```less
a{k: v !IMPORTANT;}
```

### JavaScript

```js
console.dir(require("postcss-less").parse('a{k: v !IMPORTANT;}'), {colors: true, depth: null})
```

### Expected Behavior

The declaration should be parsed as:

```
Declaration {
  prop: 'k',
  important: true,
  value: 'v'
}
```

Just like for `a{k: v !important;}`.

### Actual Behavior

The declaration is parsed as:

```
Declaration {
  prop: 'k',
  value: 'v !IMPORTANT' }
}
```

### How can we reproduce the behavior?

```js
console.dir(require("postcss-less").parse('a{k: v !IMPORTANT;}'), {colors: true, depth: null})
```

### Related

https://github.com/postcss/postcss/issues/1065

### LINKED ISSUE #102: `!important` is being moved out of mixin call parameters
* Node Version: 8.9.1
* NPM Version: 5.6.0
* postcss-less Version: 1.1.5

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
.f(
	@a : {
		color : red !important;
		background : blue;
	}
);
```

### JavaScript

```js
const fs = require('fs');
const less = require('postcss-less');
const postcss = require('postcss')

const filePath = './test.less';
const file = fs.readFileSync(filePath);
const processor = postcss();
processor.process(file, { syntax: less, from: filePath }).then(result => {
  console.log(result.root.toString());
});
```

### Expected Behavior
`result.root.toString()` should output the provided less file, completely unchanged

### Actual Behavior
output is:
```less
.f(
	@a : {
		color : red;
		background : blue;
	}
) !important;
```

### How can we reproduce the behavior?
Running the js/less provided

### LINKED ISSUE #103: Crash when parsing nested at rules (@import in media query)
* Node Version: v8.11.1
* NPM Version: v5.6.0
* postcss-less Version: v1.1.5

### LESS

```less
@media screen {
	@import "basic";
}
```

### JavaScript

n/a

### Errors 

```
TypeError: this[node.type] is not a function
    at Stringifier.stringify (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/stringifier.js:33:24)
    at Stringifier.body (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/stringifier.js:93:18)
    at Stringifier.block (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/stringifier.js:103:18)
    at Stringifier.atrule (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/stringifier.js:74:18)
    at Stringifier.stringify (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/stringifier.js:33:24)
    at stringify (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/stringify.js:14:9)
    at AtRule.toString (/Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/node.js:197:9)
    at check (/Users/timbru/work/ume/door-to-door-webapp/node_modules/stylelint/lib/rules/block-closing-brace-empty-line-before/index.js:58:41)
    at /Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/container.js:296:28
    at /Users/timbru/work/ume/door-to-door-webapp/node_modules/postcss-less/node_modules/postcss/lib/container.js:148:26
```

### Expected Behavior

Parsing should work.

### Actual Behavior

Parsing crashes.

### How can we reproduce the behavior?

`npx stylelint --syntax less '{src,styleguide}/**/*.less'` with the example less above.
PS: I am not sure if this is an upstream (postcss) issue or related to the postcss-less parsing.

### LINKED ISSUE #106: Broken resolve for `@custom-at-rule`
* Node Version: 10.2.1
* NPM Version: 6.1.0
* postcss-less Version: 2.0.0

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
@custom-selector :--camelCase .my-css-selector;
```

### JavaScript

```js
import postCssLess from 'postcss-less';
const less = `
@custom-selector :--camelCase .my-css-selector;
`;
const root = postCssLess.parse(less);
```

### Expected Behavior

Should be resolved as `at-rule`.

### Actual Behavior

Resolved as `variable`

### How can we reproduce the behavior?

Example above.

Maybe we should adopt this https://github.com/less/less.js/blob/e3c13121dfdca48ba8fe26335cc12dd3f7948676/lib/less/parser/parser.js for better detecting.

/cc @e-cloud @davidyorr looks like regression

### LINKED ISSUE #108: Wrong end position on multiline variables
_Originally reported at https://github.com/lesshint/lesshint/issues/487_

* Node Version: `10.8.0`
* NPM Version: ``
* postcss-less Version: `2.0.0`

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
@var: '
foo
bar
';
```

### JavaScript

```js
const postcss = require('postcss');
const syntax = require('postcss-less');

const lessText = `@var: '
foo
bar
';`;

postcss([])
  .process(lessText, { syntax: syntax })
  .then(function (result) {
    console.log(result.root.first)
});
```

### Expected Behavior
An AST similar to this:

```
{
  ...
  source: {
    start: { line: 1, column: 1 },
    end: { line: 4, column: 2 }
  }
}
```

### Actual Behavior
An AST looking like this (note the `end` line):

```
{
  ...
  source: {
    start: { line: 1, column: 1 },
    end: { line: 1, column: 18 }
  }
}
```

### How can we reproduce the behavior?
Run the JS example above.

The original issue used a tilde-escaped string but I've managed to reproduce it with any multiline variable. I'm not really sure how to solve it, but I'll continue to think about it.

### LINKED ISSUE #110: Error thrown on single-line mixin include without semicolon
_Originally reported at https://github.com/lesshint/lesshint/issues/490_

* Node Version: `10.9.0`
* NPM Version: `6.2.0`
* postcss-less Version: `2.0.0`

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
.foo{.bar("baz")}
```

### JavaScript

```js
const postcss = require('postcss');
const syntax = require('postcss-less');

const lessText = `.foo{.bar("baz")}`;

postcss([])
  .process(lessText, { syntax: syntax })
  .then(function (result) {
    console.log(result.root.first)
  })
  .catch((e) => {
      console.error(e);
  });
```

### Errors 

```
CssSyntaxError {
  name: 'CssSyntaxError',
  reason: 'Unknown word',
  source: '\n.foo{.bar("baz")}\n',
  line: 2,
  column: 16,
  message: '<css input>:2:16: Unknown word',
  input: { line: 2, column: 16, source: '\n.foo{.bar("baz")}\n' }
}
```

### Expected Behavior
Return an AST without any errors.

### Actual Behavior
The above error is thrown. Adding a semicolon before `}` fixes it though.

### How can we reproduce the behavior?
Run the JS code above.

### LINKED ISSUE #111: Less maps are parsed as the wrong Node type
_Originally filed at https://github.com/lesshint/lesshint/issues/492_

* Node Version: `10.10.0`
* NPM Version: `6.4.1`
* postcss-less Version: `2.0.0`

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
@var: {
    color: blue
};
```
This is apparently a new feature just released a few months ago (http://lesscss.org/features/#maps-feature).

### JavaScript

```js
const postcss= require('postcss');
const syntax = require('postcss-less');

const lessText = `@var: {
    color: blue
};`;

postcss([])
  .process(lessText, { syntax: syntax })
  .then(function (result) {
    console.log(result.root.first)
});

```

### Expected Behavior
To be parsed and returned as a `Declaration` node, like other variable assignments (e.g `@var: blue`). 

### Actual Behavior
It's parsed and returned as a `Rule` node.

### How can we reproduce the behavior?
Run the provided JS example.

### PR DESCRIPTION
**Pull request by shellscape**
Codebase refactor and update for version 3.0.0.

Tasks:
- [x] update `devDependencies`
- [x] update to PostCSS 7.x
- [x] move tests to `ava`
- [x] remove ESM, babel dependency
- [x] move from Travis CI to Circle CI
- [x] update linting
- [x] implement code coverage
- [x] fix #111
- [x] ~~fix #110~~
- [x] fix #108
- [x] ~~fix #106~~
- [x] fix #103
- [x] fix #102
- [x] fix #89
- [x] fix #88
- [x] fix #86

## Breaking Changes

- `@import` are now `AtRule` with `import: true` property
- LESS variable nodes are now `AtRule` with `variable: true` property
- LESS mixin nodes are now `Rule` or `AtRule` (depending on where they are used/declared) with `mixin: true` property
- LESS variables cannot contain whitespace  between the variable name and the colon (e.g. `@thing : value`) and will be parsed as regular CSS.
- `!important` no longer parsed separately if a space separates the `!` and `important`.

### CODE REVIEW

**Comment by shellscape** [comment]
@ai leveraging PostCSS@7, I was able to do away with a large amount of code. `lib/LessParser.js` is where most of the magic happens for some LESS-specific needs. I'm having trouble getting the base parser to recognize interpolated code, however. e.g. `@{selector}:hover { @{prop}-size: @{color} }`. If you have any ideas on how to accomplish that in the same pattern as what I've committed in aa8790f, I would appreciate it.

**Comment by ai** [comment]
> I'm having trouble getting the base parser to recognize interpolated code, however. e.g. @{selector}:hover { @{prop}-size: @{color} }

Is “base parser” `postcss/lib/parser`?

What exactly problem do you have?

**Comment by shellscape** [comment]
@ai 

> Is “base parser” postcss/lib/parser?

Yes. `lib/LessParser` extends `postcss/lib/parser`. 

> What exactly problem do you have?

`test/parser/_interpolation.js` contains examples of LESS variable interpolation. PostCSS doesn't support this sort of syntax by default (and I wouldn't expect it to). I have been using a method of overriding select methods to re-use PostCSS node types. For example, using `AtRule` as the node type and extending it with properties such as `variable: true` and `mixin: true`. I have done the same with `Comment` to allow for inline comments that are supported in LESS.

I'm attempting to use the same approach to allow parsing of interpolation identifiers. For example:

```less
@{selector}:hover { ... }
```
would be parsed as a `Rule` with a `selector` value of `'@{selector}:hover'`, just as `foo:hover { ... }` would be parsed as a `Rule` with a `selector` value of `foo:hover`. The same would go for `Declaration` nodes to allow the `prop` value to contain interpolation identifiers.

---

So far I haven't had much luck in getting things to play nicely and allow that. I tried an approach overriding `unknownWord` but had to abandon it to complete the other features. The rewrite is complete, except for Interpolation support. I will start work on that again tomorrow but wanted to ask if you could see a solution.

**Comment by ai** [comment]
I suggest you to create special token for `@{` symbols. Then you can make special logic with it in `other`.

Or you can keep current tokens, but override `parse` method.

**Comment by shellscape** [comment]
@ai interesting idea. could you share how you see that looking?

**Comment by ai** [comment]
Sorry, I will not have time for it in next few weeks, because I am preparing for conference talk.

Ask a questions.

**Comment by jwilsson** [comment]
@shellscape Wow, this looks amazing! 

You seem to have a pretty good streak going, but I'll be happy to help out with testing across downstream projects.

**Comment by shellscape** [comment]
This PR is ready for test use. @jwilsson

**Comment by thorn0** [comment]
> LESS variables cannot contain whitespace between the variable name and the colon (e.g. @thing : value) and will be parsed as regular CSS.

What is the motivation behind this? Less allows whitespace in that position.

**Pull request merged**
