### PR TITLE
Recognize CRLF as EOL in inline comments when retokenizing and add a test for that.

### PR DESCRIPTION
**Pull request by vilemj-Viclick**
**Which issue #** if any, does this resolve?
https://github.com/shellscape/postcss-less/issues/136

Please check one:
- [x] New tests created for this change
- [ ] Tests updated for this change

This PR:
- [ ] Adds new API
- [ ] Extends existing API, backwards-compatible
- [ ] Introduces a breaking change
- [x] Fixes a bug

---

This fixes a bug that is propagated to stylelint. Ultimately this would result in a new version of stylelint.

### CODE REVIEW

**Comment by vilemj-Viclick** [comment]
The Circle CI check's not passing, but this isn't my fault. It says the handlebars package is not secure, but I didn't add that package.

**Comment by shellscape** [comment]
@vilemj-Viclick thank you for opening this PR. Please update your fork from master and push. I have fixed the `npm audit` that is blocking the CI process for your PR.

**Comment by vilemj-Viclick** [comment]
Alright... I'm not exactly a git ninja (yet) and this is my first forked repo I'm contributing to. But I think I have understood and achieved what you told me to.

Is this correct?

**Comment by shellscape** [comment]
Yes, that looks correct. Thank you :)

**Pull request merged**
